version: '3.8'

services:
  quantum-safe-tls-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # Load environment variables from the .env file
      - TOKEN_SECRET=${TOKEN_SECRET}
      - PUBLIC_API_URL=${PUBLIC_API_URL}
      - PUBLIC_PORT=${PUBLIC_PORT}
      - INTERNAL_API_URL=${INTERNAL_API_URL}
      - INTERNAL_PORT=${INTERNAL_PORT}
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
    ports:
      - "443:443"
      - "9090:9090"
    volumes:
      - .:/app
    env_file:
      - .env
