services:
  quantum-safe-tls-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env  # Load environment variables from the .env file
    environment:
      - TOKEN_SECRET=${TOKEN_SECRET}
      - BACKEND_URL=${BACKEND_URL}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "443:443"
      - "9090:9090"
    volumes:
      - ./src:/app/src  # Mount the source code to allow live changes if needed
      - ./tls/certs:/etc/ssl/certs  # Mount the TLS certificates if you want to use local certs
    command: ["python", "src/main.py"]  # Override the ENTRYPOINT to run the main Python script

