app:
  environment: "production"
  debug: false

proxy:
  host: "0.0.0.0"
  port: 443

backend:
  url: "https://backend.example.com"
  host: "backend.example.com"
  port: 443

tls:
  cert_file: "/etc/ssl/certs/tls/cert.pem"
  key_file: "/etc/ssl/private/tls/key.pem"
  ca_file: "/etc/ssl/certs/ca.pem"

auth:
  enable: true
  token_secret: "prod_super_secret_key"

rate_limiter:
  enabled: true
  max_requests_per_minute: 100

monitoring:
  metrics_port: 9090

renewal:
  enable_auto_renewal: true
  renewal_check_interval: 86400
