alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - localhost:9093
global:
  scrape_interval: 15s
rule_files:
- alert_rules.yml
scrape_configs:
- job_name: proxy_metrics
  static_configs:
  - targets:
    - localhost:9090
